# Plotly

## Introducción

Plotly Express es una biblioteca de visualización de datos de alto nivel, construida sobre la biblioteca Plotly. Su principal objetivo es permitir la creación de gráficos estadísticos atractivos e interactivos con muy pocas líneas de código.
Posee una amplia variedad de recursos y gráficos únicos, estadísticos, geográficos, científicos, econométricos y tridimensionales.

Al igual que Matplotlib y Seaborn, se pueden combinar los valores **numéricos** y **categóricos** y se combina para trabajar con pandas de forma simple.
[plotly documentos](https://plotly.com/python/)

### ¿En qué casos se usa?
Se utiliza principalmente para el análisis exploratorio de datos (EDA). Es ideal cuando necesitas entender rápidamente la distribución, la relación y la composición de tus datos. Algunos ejemplos comunes de gráficos que puedes crear son:

**Gráficos de dispersión** para ver la relación entre dos variables.

**Gráficos de líneas** para observar tendencias a lo largo del tiempo.

**Histogramas y diagramas de caja** para entender la distribución de una variable.

**Gráficos de barras** para comparar categorías.

**Mapas para visualizar** datos geográficos.

**Gráficos circulares y de torta** para mostrar proporciones.

## Instalación e importación

Recuerda que puede ser necesario instalarlo
```
pip install plotly
```

statsmodels es un módulo de Py con clases y fx para la estimación de diferentes modelos estadísticos
y para realizar pruebas y exploración de datos estadísticos
Documentación: https://www.statsmodels.org/stable/index.html

In [ ]:
!pip install statsmodels==0.14.0
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly.express as px

Collecting statsmodels==0.14.0
  Downloading statsmodels-0.14.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 139.8 MB/s eta 0:00:00
Collecting patsy>=0.5.2
  Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.9/232.9 kB 60.5 MB/s eta 0:00:00
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /root/venv/lib/python3.9/site-packages (from statsmodels==0.14.0) (1.9.3)
Requirement already satisfied: packaging>=21.3 in /root/venv/lib/python3.9/site-packages (from statsmodels==0.14.0) (25.0)
Requirement already satisfied: numpy>=1.18 in /root/venv/lib/python3.9/site-packages (from statsmodels==0.14.0) (1.25.2)
Requirement already satisfied: pandas>=1.0 in /root/venv/lib/python3.9/site-packages (from statsmodels==0.14.0) (2.1.4)
Requirement already satisfied: pytz>=2020.1 in /root/venv/lib/python3.9/site-packages (from pandas>=1.0->statsmodels==0.14.0) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/venv/lib/python3.9/site-packages (from pandas>=1.0->statsmodels==0.14.0) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in /root/venv/lib/python3.9/site-packages (from pandas>=1.0->statsmodels==0.14.0) (2025.2)
Requirement already satisfied: six>=1.5 in /root/venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.0->statsmodels==0.14.0) (1.17.0)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-1.0.1 statsmodels-0.14.0

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

## Ipython

IPython potencia el intérprete de Python orientado a exploración e interactividad. El módulo display proporciona herramientas de visualización en IPython
Documentación

In [ ]:
from IPython.display import display as ds

## Dataset

In [ ]:
df_tips = px.data.tips()
ds(df_tips)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Barras

In [ ]:
px.bar(df_tips, x='day', y="total_bill", color="smoker",barmode="group", title='Valor de la cuenta x día / fumador/no fumador')

### Histogramas

In [ ]:
px.histogram(df_tips, x='total_bill', title='Valor total de la cuenta')

In [ ]:
# Valores estadisticos
def calcular_medidas_tendencia_central(df, column):
    promedio = df[column].mean()
    mediana = df[column].median()
    moda = df[column].mode().iloc[0]
    return promedio, mediana, moda

In [ ]:
promedio, mediana, moda = calcular_medidas_tendencia_central(df_tips, 'total_bill')
print(f"El Promedio es: {promedio:.2f}")
print(f"La Mediana es: {mediana:.2f}")
print(f"La Moda es: {moda:.2f}")

# 2. Crear el histograma base
fig = px.histogram(df_tips, x='total_bill', title='Distribución del Valor Total de la Cuenta')

# 3. Añadir las líneas verticales para la mediana y la moda
fig.add_vline(x=mediana,
              line_width=3,
              line_dash="dash", # Estilo de línea
              line_color="red", # Color
              annotation_text=f'Mediana: {mediana:.2f}', # Etiqueta
              annotation_position="top right")

fig.add_vline(x=moda,
              line_width=3,
              line_dash="dot", # Estilo de línea diferente
              line_color="green", # Color diferente
              annotation_text=f'Moda: {moda:.2f}',
              annotation_position="top left")

fig.show()

El Promedio es: 19.79
La Mediana es: 17.80
La Moda es: 13.42

In [ ]:
px.histogram(df_tips, x='total_bill', title='Valor total de la cuenta', color='smoker')

In [ ]:
px.histogram(df_tips, 'day', title='Comensales por día')

In [ ]:
# ORDENO EL EJE x
px.histogram(df_tips, 'day', title='Comensales por día', category_orders={'day':['Thur','Fri','Sat','Sun']}, color="smoker")

In [ ]:
px.histogram(df_tips, 'day', title='Comensales por día', category_orders={'day':['Thur','Fri','Sat','Sun']}, color='sex')

### Boxplot

In [ ]:
px.box(df_tips,x='total_bill',title='Valor total de la cuenta')

In [ ]:
px.box(df_tips,y='total_bill',title='Valor total de la cuenta', color='smoker')

In [ ]:
px.box(df_tips,y='total_bill',x='day',title='Valor total de la cuenta', color='smoker')

In [ ]:
px.box(df_tips,y='total_bill',x='day',title='Valor total de la cuenta', color='smoker', boxmode='overlay')

### Violin plot

In [ ]:
px.violin(df_tips,y='total_bill',x='day',title='Valor total de la cuenta', color='smoker')
# overlay -- > violinmode='overlay'

### StripPlot

In [ ]:
px.strip(df_tips,y='total_bill',x='day',title='Valor total de la cuenta', color='smoker')
# overlay -- > stripmode='overlay'

### Scatterplot

In [ ]:
df_gapminder = px.data.gapminder()
df_gapminder

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
df_2007 = df_gapminder.query('year==2007')
df_2007

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
...,...,...,...,...,...,...,...,...
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
px.scatter(df_2007, x='gdpPercap', y='lifeExp')

In [ ]:
px.scatter(df_2007, x='gdpPercap', y='lifeExp', color='continent')

In [ ]:
px.scatter(df_2007, x='gdpPercap', y='lifeExp', color='continent', hover_name='country')

In [ ]:
px.scatter(df_2007, x='gdpPercap', y='lifeExp', color='continent', hover_name='country', size='pop', size_max=60)

In [ ]:
# linea de tendencia -- > trendline ='ols' --> del módulo statsmodel
px.scatter(df_tips, x='total_bill', y='tip', trendline='ols')

In [ ]:
px.scatter(df_tips, x='total_bill', y='tip', trendline='ols', color='day')

### HeatMap

In [ ]:
df_flight = sns.load_dataset('flights')
df_flight

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [ ]:
df_flight_pv = df_flight.pivot_table(index='month', columns='year', values='passengers')
df_flight_pv

year,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960
month,,,,,,,,,,,,
Jan,112.0,115.0,145.0,171.0,196.0,204.0,242.0,284.0,315.0,340.0,360.0,417.0
Feb,118.0,126.0,150.0,180.0,196.0,188.0,233.0,277.0,301.0,318.0,342.0,391.0
Mar,132.0,141.0,178.0,193.0,236.0,235.0,267.0,317.0,356.0,362.0,406.0,419.0
Apr,129.0,135.0,163.0,181.0,235.0,227.0,269.0,313.0,348.0,348.0,396.0,461.0
May,121.0,125.0,172.0,183.0,229.0,234.0,270.0,318.0,355.0,363.0,420.0,472.0
Jun,135.0,149.0,178.0,218.0,243.0,264.0,315.0,374.0,422.0,435.0,472.0,535.0
Jul,148.0,170.0,199.0,230.0,264.0,302.0,364.0,413.0,465.0,491.0,548.0,622.0
Aug,148.0,170.0,199.0,242.0,272.0,293.0,347.0,405.0,467.0,505.0,559.0,606.0
Sep,136.0,158.0,184.0,209.0,237.0,259.0,312.0,355.0,404.0,404.0,463.0,508.0
Oct,119.0,133.0,162.0,191.0,211.0,229.0,274.0,306.0,347.0,359.0,407.0,461.0
Nov,104.0,114.0,146.0,172.0,180.0,203.0,237.0,271.0,305.0,310.0,362.0,390.0
Dec,118.0,140.0,166.0,194.0,201.0,229.0,278.0,306.0,336.0,337.0,405.0,432.0

In [ ]:
px.imshow(df_flight_pv)

### Animaciones

In [ ]:
px.scatter(df_gapminder, x='gdpPercap', y='lifeExp', color='continent', hover_name='country', size='pop', size_max=60)

In [ ]:
#acomodo el rango de los ejes
px.scatter(df_gapminder, x='gdpPercap', y='lifeExp', color='continent', hover_name='country', size='pop', size_max=60, range_x=[100,100000], range_y=[25,90])

In [ ]:
# aplico escala log al eje x
px.scatter(df_gapminder, x='gdpPercap', y='lifeExp', color='continent', hover_name='country', size='pop', size_max=60, range_x=[100,100000], range_y=[25,90], log_x=True)

In [ ]:
# animacion
px.scatter(df_gapminder, x='gdpPercap', y='lifeExp', color='continent', hover_name='country', size='pop', size_max=60, range_x=[100,100000], range_y=[25,90], log_x=True, animation_frame='year', animation_group='country')

In [ ]:
ds(df_gapminder)
ds(df_tips)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# Mostramos los primeros 5 registros del dataframe para entender su estructura
print("Vista previa del dataset de propinas:")
ds(df_tips.head())

# Creamos un gráfico de dispersión interactivo
# Puedes pasar el cursor sobre los puntos para ver los datos exactos.
fig_scatter = px.scatter(df_tips,
                         x='total_bill',
                         y='tip',
                         color='sex', # Color por género
                         facet_col='day', # Crea una columna por cada día
                         title='Relación Cuenta Total vs. Propina por Día y Género',
                         labels={'total_bill': 'Cuenta Total ($)', 'tip': 'Propina ($)', 'sex': 'Género'})

# Creamos un boxplot para ver la distribución de la cuenta total por día
fig_box = px.box(df_tips,
                 x='day',
                 y='total_bill',
                 color='smoker', # Diferenciamos entre fumadores y no fumadores
                 title='Distribución de la Cuenta Total por Día (Fumadores vs. No Fumadores)',
                 labels={'day': 'Día de la Semana', 'total_bill': 'Cuenta Total ($)', 'smoker': 'Fumador'})


# Usamos ds() para mostrar ambos gráficos en la misma celda
print("\n--- Gráficos Interactivos ---")
ds(fig_scatter)
ds(fig_box)

Vista previa del dataset de propinas:

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

--- Gráficos Interactivos ---